spring:
  application:
    name: auth
  datasource:
    url: jdbc:h2:mem:mailsdb;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml
    enabled: true

external:
  api:
    calendar-base-url: https://app.usergems.com/api/hiring/calendar-challenge/events
    person-base-url: https://app.usergems.com/api/hiring/calendar-challenge/person/